# Generated by Django 5.0 on 2023-12-09 18:31

from django.db import migrations


def populate_status(apps, schemaeditor):
    entries = {
        "to do": "An issue that needs to be started",
        "in progress": "An issue being worked on",
        "done": "An issue for which work has been completed"
    }
    Status = apps.get_model("issues", "Status")
    for key, value in entries.items():
        status_obj= Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_delete_post'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
